### ISSUE TITLE
Greetings Johan! The future of "dusage"

### ISSUE THREAD

**Issue by johnsonjh** [sciurius/dusage#1]
Hello @sciurius,

First off, I'm sorry I didn't contact you via e-mail first - that might have been more appropriate.  

I took it upon myself to put your `duage` tool on-line "again" because - mostly because it seemed to have lost it's permanent home, and, surely scary for both of us, it happens to be one of the oldest tools that I continually use and rely on, next to "ircII". I didn't see it listed on your [software page](https://www.vromans.org/johan/software.html) or anywhere else.  

I believe I originally received it from a mailing list (via UUCP), or Usenet, around 1990 or 1991.

For a few years, beginning in [2006](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=92139), I "maintained" a [FreeBSD port](https://www.freshports.org/sysutils/dusage/) of your useful little utility, but (take no offense), it was determined to be unsuitable for inclusion in Debian and Fedora. Similar to the situation with `afio`, this was "proprietary and restricted-use software", because of the 'hippy' *'Peaceware'* license. 

While that wouldn't have been my choice of a license, I absolutely respected your wishes, and complied, as fully as possible, with the licensing terms. However, the FreeBSD people weren't happy with "Peaceware" after awhile... they not only removed it, maybe rightfully so, from physical media distribution, (as that was considered to be a 'sale', and in violation of the license), but also from the on-line ["distfiles"](http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/ports/distfiles/) archive, which I must assume is automatically used in building the media. Unfortunately, this was the primary home for your little utility at the time.

Because I wasn't hosting anything permanently for a stretch, it became unfetchable, and was dropped from FreeBSD [at the end of 2008](https://www.freshports.org/commit.php?category=sysutils&port=dusage&files=yes&message_id=200812071949.mB7JndIT016776@repoman.freebsd.org). Eventually, free Usenet access went away... *"Walnut Creek"*'s FTP site went away... *"tsx-11.mit.edu"* went away... SunSite became iBiblio (and it disappeared from there), it [wasn't on CPAN](https://metacpan.org/search?size=5000&q=dusage)... so, once again, it was gone, or at least overshadowed by some Novell NetWare tool with [the same name](ftp://major.butt.care/mirrors/cd.textfiles.com/cream07/lan/dusage.zip).

For what it's worth, I made never made any updates or changes to your tool beyond what minimal minutiae was required for it to continue to work, and then mangling it a bit with `perltidy`. It continues to serve me well.

I'm glad that you placed it on-line, and now, I have a few questions for you. Would you like for me to remove by repository? If you plan to keep yours, it's redundant. Also, since you imported your release tags, I assume, from *CVS*, clearly, your repository is better than mine. It's my opinion that the other mirrors I made are also redundant and confusing as well, and should be converted to strictly mirror of your repository. Let me know if you have other wishes.

I originally requested requested issue tracking on our own issue tracker, mainly to not bother you, if you didn't want to be bothered. If it's OK with you, I can remove that as well, and I'd happily point everything prominently to your GitHub account. 

I also see you re-licensed the utility. I wanted to clarify that you explicitly meant that `dusage` is now available under the [Artistic License](https://perldoc.perl.org/perlartistic) going forward. If so, I'd make set it up so GitHub properly recognizes the license terms and indexes it correctly, and add some monitoring actions to the repo as well, if you'd like.  Not sure what you think of my `perltidy`'d version, or if you prefer your original formatting.

Thank you for your utility, and good to be in contact with you.

**Comment by sciurius** [comment]
Actually I'm mostly glad you brought this tool under my attention. Yes, I've been using it for more that 30 years and fiddled a bit to keep modern Perl satisfied but it is still mostly the same as 30 years ago. It may need a bit of cleaning up, mostly the files that go with it and make a 'new' (FWIW) release on Github and CPAN so it has a home (and well-defined state) again. I was aware of the Peaceware problem that's why I changed it to Artistic some time ago.

AFAIC you don't need to remove your repo. It clearly indicates that it is based on the original version. 

I see no added benefits from `perltydy`ing so I'd prefer to leave the style as it is now. You know that every character modified may introduce new bugs ;). Besides, I think I've already made some style improvements with the Perl5 update.

One of the charming aspects of this program is that is is a single-file program. Modern Perl standards (since Perl5 -- 26 years ago) are module-oriented, so a real modernized tool would consist of at least one module (e.g. App::Dusage) and a script (script/dusage) to invoke it. While I'm not really in favour of this approach I do not mind going that direction. What do you think?

**Comment by johnsonjh** [comment]
Honestly, that's the really is no need for all that modularity in such a simple tool - also, perhaps someone somewhere still wants to run it on Perl 4 (or something) - anyway, I see no benefit.

I respect your view on the `perltidy` changes.  I'm not a Perl user by any means (just a few tasks and one-liners here and there), so I'll respect your lead here.

I think I'll prepare a PR with what's needed for a "proper" GitHub release based on cloning your sources, adopting your change from Peaceware to Artistic licensing, and send you a PR sometime this week for you to review.

By any chance do you have a CONTRIBUTOR listing or ChangeLog of some kind? I don't think it's necessary to rewrite the repo's history, but it would be nice to include, if they are available.

**Comment by sciurius** [comment]
The modularity is mere cosmetic, since the current version requires Perl5 anyway. It won't run on Perl4 which is very extinct. Even older Perl5 versions should be avoided. Personally I lay the bar at 5.10.1 since that is the first version of the current generation of Perl5. It is also the first version to have decent Unicode support and it is the oldest version that I have on my system for testing. 5.10.1 went end of life on 2009-08-23.

An additional complication is that CPAN, where all Perl material ought to be, is still not script-friendly. A kit will not be published unless it has at least one module. It will be stored but will not enter the search engines. I must look into that.

I've checked in a Changes file.

**Comment by sciurius** [comment]
Reworked some files and added some more. It is now a decent CPAN kit.

**Comment by johnsonjh** [comment]
Sorry, been busy with work this week, but I plan to update my repo to yours and give you a PR with an slightly expanded README - probably not much else to do.  Thanks for the updates!

**Comment by johnsonjh** [comment]
https://github.com/sciurius/dusage/pull/2 as promised.

**Comment by sciurius** [comment]
Hi Jeffrey,
I applied a selection of your changes to the master. I didn't incorporate all the new and fancy files and changes that I don't see a real use for.

I attributed the changes to you. Thanks for contributing and giving me the incentive to wipe the dust off :) .
